# CBR-RAG Evaluation on PubMedQA using Gemma

This notebook runs:
- `no_rag`
- `keyword_rag`
- `semantic_rag`
- `cbr_rag`

using the fixed evaluation IDs from `test_ids_250.json`.

In [6]:
!pip install biopython sentence-transformers faiss-cpu requests python-dotenv --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 106.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 86.0 MB/s eta 0:00:00

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
import json
import os
import re
import sys
import textwrap
from collections import Counter

import numpy as np
from Bio import Entrez
from openai import OpenAI
from sentence_transformers import SentenceTransformer
from tqdm.auto import tqdm

# Add the directory containing the modules to sys.path
sys.path.append('/content/drive/MyDrive/Colab Notebooks/NLP Notebooks')
from cbr_retrieval import PubMedQACaseRetriever

In [ ]:
import os

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

MODEL_NAME = "google/gemma-3-12b-it"

TOP_K_DOCS = 6
SEMANTIC_CANDIDATES = 40
GRAPH_SEED_K = 25
CBR_TOP_CASES = 4
GRAPH_BUILD_LIMIT = None
CASE_BUILD_LIMIT = None

Entrez.email = "rithvikhariprasad@gmail.com"
Entrez.tool = "pubmed-cbr-rag"

QUESTIONS_FILE = "/content/drive/MyDrive/ori_pqal.json"
GROUND_TRUTH_FILE = "/content/drive/MyDrive/test_ground_truth.json"
#TEST_IDS_FILE = "/content/drive/MyDrive/test_ids_250.json"

if not OPENROUTER_API_KEY:
    raise ValueError("Set OPENROUTER_API_KEY before running this notebook.")

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY,
)

emb_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

pubmed_search_cache = {}
graph_retriever = None
case_retriever = None

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
test = client.chat.completions.create(
    model="google/gemma-3-12b-it",
    messages=[{"role": "user", "content": "Reply with only: working"}],
    max_tokens=5,
    temperature=0.0,
)
print(test.choices[0].message.content)

working

In [ ]:
def extract_answer(llm_output):
    if not llm_output:
        return "unknown"
    match = re.search(r"<answer>(.*?)</answer>", llm_output, flags=re.IGNORECASE | re.DOTALL)
    if match:
        ans = match.group(1).strip().lower()
        ans = re.sub(r"[^a-z]", "", ans)
        if ans in ["yes", "no", "maybe"]:
            return ans
    return "unknown"

def _normalize_embeddings(matrix):
    matrix = matrix.astype("float32")
    matrix /= (np.linalg.norm(matrix, axis=1, keepdims=True) + 1e-12)
    return matrix

def _doc_text(doc):
    return f"{doc.get('title', '')} {doc.get('abstract', '')}".strip()

def pubmed_keyword_search(query: str, k: int = 5, verbose: bool = False):
    cache_key = (query, k)
    if cache_key in pubmed_search_cache:
        return [dict(doc) for doc in pubmed_search_cache[cache_key]]

    h = Entrez.esearch(db="pubmed", term=query, retmax=k)
    r = Entrez.read(h)
    h.close()
    pmids = r.get("IdList", [])
    if not pmids:
        pubmed_search_cache[cache_key] = []
        return []

    h = Entrez.efetch(db="pubmed", id=",".join(pmids), rettype="abstract", retmode="xml")
    recs = Entrez.read(h)
    h.close()
    if verbose:
        print("ESearch Count:", r["Count"], "Returning:", len(r["IdList"]))

    docs = []
    for article in recs["PubmedArticle"]:
        art = article["MedlineCitation"]["Article"]
        pmid = str(article["MedlineCitation"]["PMID"])
        title = str(art.get("ArticleTitle", ""))
        abstract_list = art.get("Abstract", {}).get("AbstractText", [])
        abstract = " ".join(str(x) for x in abstract_list)
        docs.append({"pmid": pmid, "title": title, "abstract": abstract})

    pubmed_search_cache[cache_key] = [dict(doc) for doc in docs]
    return docs

def semantic_topk_from_pubmed(query: str, k: int = 5, n_candidates: int = 40):
    candidates = pubmed_keyword_search(query, k=n_candidates)
    if not candidates:
        return []

    texts = [_doc_text(d) for d in candidates]
    q_emb = _normalize_embeddings(emb_model.encode([query], convert_to_numpy=True))
    d_emb = _normalize_embeddings(emb_model.encode(texts, convert_to_numpy=True))

    semantic_scores = d_emb @ q_emb[0]
    lexical_scores = np.array([lexical_overlap_score(query, text) for text in texts], dtype="float32")
    final_scores = 0.85 * semantic_scores + 0.15 * lexical_scores
    order = np.argsort(-final_scores)[:k]

    results = []
    for idx in order:
        d = dict(candidates[int(idx)])
        d["score"] = float(final_scores[int(idx)])
        d["semantic_score"] = float(semantic_scores[int(idx)])
        d["lexical_score"] = float(lexical_scores[int(idx)])
        results.append(d)
    return results

def graph_topk_from_pubmedqa(query: str, k: int = 5, seed_k: int = 25):
    if graph_retriever is None:
        raise ValueError("Build the graph index first.")
    return graph_retriever.retrieve(query, k=k, seed_k=seed_k)

def cbr_topk_from_pubmedqa(query: str, k_cases: int = 4):
    if case_retriever is None:
        raise ValueError("Build the case base first.")
    return case_retriever.retrieve(query, k=k_cases)

def build_context(docs, max_chars=6000):
    parts = []
    for i, d in enumerate(docs, start=1):
        snippet = d["abstract"][:1200]
        parts.append(f"[{i}] PMID: {d['pmid']}\nTitle: {d['title']}\nAbstract: {snippet}\n")
    return "\n\n".join(parts)[:max_chars]

def build_case_context(cases, max_chars=3500):
    parts = []
    for i, case in enumerate(cases, start=1):
        rationale = (case.get("long_answer") or "").strip()
        if rationale:
            rationale = rationale[:500]
        elif case.get("contexts"):
            rationale = " ".join(case["contexts"][:2])[:500]
        else:
            rationale = "No rationale available."
        parts.append(
            f"[Case {i}] Similar question: {case['question']}\n"
            f"Final answer: {case['final_decision']}\n"
            f"Reasoning pattern: {rationale}\n"
        )
    return "\n\n".join(parts)[:max_chars]

def build_rag_prompts(user_query, docs):
    ctx = build_context(docs)
    system_msg = (
        "You are a careful biomedical question answering assistant. "
        "Use only the provided evidence. "
        "Answer 'yes' only when the evidence clearly supports the claim. "
        "Answer 'no' when the evidence clearly contradicts the claim or fails to support it. "
        "Answer 'maybe' only when the evidence is genuinely mixed or insufficient."
    )
    user_msg = textwrap.dedent(f"""Question: {user_query}

    PubMed sources:
    {ctx}

    When answering:
    - Think briefly inside <thinking> tags.
    - Then output exactly one final label in <answer> tags: yes, no, or maybe.
    - Prefer 'no' over 'maybe' when the evidence does not support the claim.
    - Do not invent facts not present in the sources.""")
    return system_msg, user_msg

def build_cbr_prompts(user_query, docs, cases):
    evidence_ctx = build_context(docs, max_chars=4500)
    case_ctx = build_case_context(cases, max_chars=2500)
    system_msg = (
        "You are a careful biomedical question answering assistant using case-based reasoning. "
        "Use similar past PubMedQA cases as reasoning patterns only, and use the current PubMed evidence as the factual basis for the final answer. "
        "Do not copy a past answer unless the current evidence supports it."
    )
    user_msg = textwrap.dedent(f"""Target question: {user_query}

    Similar past QA cases:
    {case_ctx}

    Current PubMed evidence:
    {evidence_ctx}

    Instructions:
    - First compare the target question to the similar past cases inside <thinking> tags.
    - Use the current PubMed evidence to verify whether the same reasoning applies.
    - Then output exactly one final label in <answer> tags: yes, no, or maybe.
    - If the past cases conflict with the current evidence, trust the current evidence.
    - Prefer 'no' over 'maybe' when the evidence does not support the claim.
    - Do not invent facts not present in the provided cases or evidence.""")
    return system_msg, user_msg

def call_model(system_prompt, user_prompt, max_tokens=256):
    completion = client.chat.completions.create(
        extra_headers={
            "HTTP-Referer": "<YOUR_SITE_URL>",
            "X-OpenRouter-Title": "<YOUR_SITE_NAME>",
        },
        extra_body={},
        model=MODEL_NAME,
        temperature=0.0,
        max_tokens=max_tokens,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    )
    return completion.choices[0].message.content

In [ ]:

print("Loading datasets...")
with open(QUESTIONS_FILE, "r", encoding="utf-8") as f:
    questions_data = json.load(f)

with open(GROUND_TRUTH_FILE, "r", encoding="utf-8") as f:
    gt_data = json.load(f)


test_ids = [
    str(q_id)
    for q_id in gt_data.keys()
    if str(q_id) in questions_data
]

print(f"Loaded {len(test_ids)} test IDs from ground truth file")

label_counts = Counter()
for q_id in test_ids:
    gt_entry = gt_data[q_id]
    if isinstance(gt_entry, dict):
        label = gt_entry.get("final_decision", "").strip().lower()
    else:
        label = str(gt_entry).strip().lower()
    label_counts[label] += 1
print("Sample label counts:", dict(label_counts))

print("Building PubMedQA graph index...")
graph_retriever = PubMedQAGraphRetriever(
    emb_model=emb_model,
    graph_k=10,
    diffusion_alpha=0.60,
    diffusion_steps=8,
    seed_k=GRAPH_SEED_K,
).fit(questions_data, max_questions=GRAPH_BUILD_LIMIT)
print(f"Graph index ready with {len(graph_retriever.documents)} context nodes.")

print("Building PubMedQA case base for CBR-RAG...")
case_retriever = PubMedQACaseRetriever(emb_model=emb_model).fit(
    questions_data,
    gt_data=gt_data,
    excluded_ids=test_ids,
    max_cases=CASE_BUILD_LIMIT,
)
print(f"Case base ready with {len(case_retriever.cases)} train cases.")

Loading datasets...
Loaded 500 test IDs from ground truth file
Sample label counts: {'yes': 276, 'no': 169, 'maybe': 55}
Building PubMedQA graph index...

Batches:   0%|          | 0/105 [00:00<?, ?it/s]

Graph index ready with 3358 context nodes.
Building PubMedQA case base for CBR-RAG...
Case base ready with 500 train cases.

In [ ]:
import os
import ast
import pandas as pd
from tqdm import tqdm
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    classification_report,
    confusion_matrix
)

LABELS = ["yes", "no", "maybe"]

CHECKPOINT_PATH = "/content/drive/MyDrive/rag_checkpoint_cbr500.csv"
SAVE_EVERY = 50

def get_ground_truth(q_id):
    gt_entry = gt_data[q_id]
    if isinstance(gt_entry, dict):
        return gt_entry.get("final_decision", "").strip().lower()
    return str(gt_entry).strip().lower()


def get_pmids_from_docs(docs):
    pmids = []
    for d in docs:
        if isinstance(d, dict):
            pmid = d.get("pmid") or d.get("pubmed_id") or d.get("PMID")
            if pmid is not None:
                pmids.append(str(pmid))
    return pmids


def add_prediction(all_rows, q_id, method, query, gold, pred, docs=None, error=None):
    docs = docs or []
    all_rows.append({
        "qid": str(q_id),
        "method": method,
        "question": query,
        "gold": gold,
        "pred": pred,
        "retrieved_pmids": get_pmids_from_docs(docs),
        "error": error
    })


# Resume checkpoint
if os.path.exists(CHECKPOINT_PATH):
    checkpoint_df = pd.read_csv(CHECKPOINT_PATH)

    # convert retrieved_pmids back from string to list
    if "retrieved_pmids" in checkpoint_df.columns:
        checkpoint_df["retrieved_pmids"] = checkpoint_df["retrieved_pmids"].apply(
            lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith("[") else []
        )

    all_predictions = checkpoint_df.to_dict("records")

    # done only when all selected methods exist for that qid
    done_ids = set(checkpoint_df["qid"].astype(str).unique())

    print(f"▶️ Resuming from checkpoint — {len(done_ids)} question IDs already attempted.")
else:
    all_predictions = []
    done_ids = set()
    print("🆕 Starting fresh.")

▶️ Resuming from checkpoint — 250 question IDs already attempted.

In [ ]:
# =========================
# MAIN EVALUATION LOOP WITH CHECKPOINTING
# =========================

failed_qids = []

for i, q_id in enumerate(tqdm(test_ids, desc="Evaluating RAG Pipelines")):
    q_id = str(q_id)

    if q_id in done_ids:
        continue

    try:
        query = questions_data[q_id].get("QUESTION", "")
        ground_truth = get_ground_truth(q_id)

        # Skip invalid labels
        if ground_truth not in LABELS:
            failed_qids.append((q_id, f"Invalid gold label: {ground_truth}"))
            continue

        # ---------- No RAG ----------
        ans_no_rag = extract_answer(
            call_model(*build_rag_prompts(query, []))
        )
        add_prediction(
            all_predictions, q_id, "no_rag", query, ground_truth, ans_no_rag, docs=[]
        )

        # ---------- Keyword RAG ----------
        docs_keyword = pubmed_keyword_search(query, k=TOP_K_DOCS)
        ans_kw = extract_answer(
            call_model(*build_rag_prompts(query, docs_keyword))
        )
        add_prediction(
            all_predictions, q_id, "keyword_rag", query, ground_truth, ans_kw, docs=docs_keyword
        )

        # ---------- Semantic RAG ----------
        docs_semantic = semantic_topk_from_pubmed(
            query,
            k=TOP_K_DOCS,
            n_candidates=SEMANTIC_CANDIDATES
        )
        ans_sem = extract_answer(
            call_model(*build_rag_prompts(query, docs_semantic))
        )
        add_prediction(
            all_predictions, q_id, "semantic_rag", query, ground_truth, ans_sem, docs=docs_semantic
        )

        # ---------- CBR RAG ----------
        cbr_cases = cbr_topk_from_pubmedqa(query, k_cases=CBR_TOP_CASES)
        cbr_docs = docs_semantic if docs_semantic else docs_keyword
        ans_cbr = extract_answer(
            call_model(*build_cbr_prompts(query, cbr_docs, cbr_cases))
        )

        # For retrieved_pmids, store both evidence docs and CBR cases if possible
        combined_docs = []
        if cbr_docs:
            combined_docs.extend(cbr_docs)
        if cbr_cases:
            combined_docs.extend(cbr_cases)

        add_prediction(
            all_predictions, q_id, "cbr_rag", query, ground_truth, ans_cbr, docs=combined_docs
        )

        done_ids.add(q_id)

        print(f"\n--- Question ID: {q_id} ---")
        print(f"Ground Truth:   {ground_truth}")
        print(f"No RAG Output:  {ans_no_rag}")
        print(f"Keyword RAG:    {ans_kw}")
        print(f"Semantic RAG:   {ans_sem}")
        print(f"CBR RAG:        {ans_cbr}")

        # Save checkpoint
        if len(done_ids) % SAVE_EVERY == 0:
            temp_df = pd.DataFrame(all_predictions)
            temp_df.to_csv(CHECKPOINT_PATH, index=False)
            print(f"💾 Checkpoint saved at {len(done_ids)} completed questions.")

    except Exception as e:
        failed_qids.append((q_id, str(e)))
        print(f"\nSkipped Question ID {q_id} due to error: {e}")

        # Save even after error
        temp_df = pd.DataFrame(all_predictions)
        temp_df.to_csv(CHECKPOINT_PATH, index=False)

# Final save
pred_df = pd.DataFrame(all_predictions)
pred_df.to_csv(CHECKPOINT_PATH, index=False)

print(f"\nFinal checkpoint saved: {CHECKPOINT_PATH}")
print(f"Total prediction rows: {len(pred_df)}")
print(f"Total question IDs completed: {len(done_ids)}")

Evaluating RAG Pipelines:   1%|          | 3/500 [00:09<27:29,  3.32s/it]

--- Question ID: 19100463 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:   1%|          | 5/500 [00:21<38:04,  4.62s/it]

--- Question ID: 12913878 ---
Ground Truth:   yes
No RAG Output:  yes
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:   1%|▏         | 7/500 [00:29<34:41,  4.22s/it]

--- Question ID: 25475395 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    unknown
Semantic RAG:   unknown
CBR RAG:        no

Evaluating RAG Pipelines:   2%|▏         | 8/500 [00:42<51:06,  6.23s/it]

--- Question ID: 19130332 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    maybe
Semantic RAG:   no
CBR RAG:        maybe

Evaluating RAG Pipelines:   2%|▏         | 9/500 [01:01<1:16:57,  9.41s/it]

--- Question ID: 9427037 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:   2%|▏         | 12/500 [01:18<1:00:54,  7.49s/it]

--- Question ID: 22680064 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:   3%|▎         | 15/500 [01:34<53:01,  6.56s/it]

--- Question ID: 21726930 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:   4%|▎         | 18/500 [01:53<52:36,  6.55s/it]

--- Question ID: 26370095 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:   4%|▍         | 19/500 [02:12<1:07:05,  8.37s/it]

--- Question ID: 18041059 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:   4%|▍         | 20/500 [02:27<1:16:45,  9.59s/it]

--- Question ID: 15041506 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:   4%|▍         | 21/500 [02:38<1:19:05,  9.91s/it]

--- Question ID: 11146778 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:   4%|▍         | 22/500 [02:52<1:25:49, 10.77s/it]

--- Question ID: 27281318 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:   5%|▌         | 26/500 [03:03<48:58,  6.20s/it]

--- Question ID: 15995461 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:   5%|▌         | 27/500 [03:17<59:58,  7.61s/it]

--- Question ID: 21850494 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:   6%|▌         | 28/500 [03:29<1:05:28,  8.32s/it]

--- Question ID: 19106867 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:   6%|▋         | 32/500 [03:39<41:03,  5.26s/it]

--- Question ID: 26879871 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:   8%|▊         | 38/500 [03:54<29:16,  3.80s/it]

--- Question ID: 17682349 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:   8%|▊         | 39/500 [04:12<41:49,  5.44s/it]

--- Question ID: 17355582 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:   8%|▊         | 40/500 [04:23<47:11,  6.16s/it]

--- Question ID: 15597845 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:   8%|▊         | 42/500 [04:35<47:22,  6.21s/it]

--- Question ID: 27549226 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        yes

Evaluating RAG Pipelines:   9%|▊         | 43/500 [04:50<58:39,  7.70s/it]

--- Question ID: 26348845 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:   9%|▉         | 46/500 [05:03<47:40,  6.30s/it]

--- Question ID: 26548832 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        no

Evaluating RAG Pipelines:  10%|▉         | 49/500 [05:15<40:53,  5.44s/it]

--- Question ID: 24622801 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  10%|█         | 51/500 [05:31<45:32,  6.09s/it]

--- Question ID: 20577124 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  11%|█         | 54/500 [05:47<43:11,  5.81s/it]

--- Question ID: 27858166 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  11%|█         | 56/500 [06:08<51:28,  6.96s/it]

--- Question ID: 16266387 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  12%|█▏        | 60/500 [06:19<38:26,  5.24s/it]

--- Question ID: 18594195 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    unknown
Semantic RAG:   unknown
CBR RAG:        maybe

Evaluating RAG Pipelines:  12%|█▏        | 61/500 [06:38<50:55,  6.96s/it]

--- Question ID: 22497340 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  13%|█▎        | 63/500 [06:48<47:26,  6.51s/it]

--- Question ID: 20571467 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  13%|█▎        | 67/500 [07:07<40:54,  5.67s/it]

--- Question ID: 23810330 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  14%|█▎        | 68/500 [07:17<44:50,  6.23s/it]

--- Question ID: 15151701 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  14%|█▍        | 69/500 [07:26<48:36,  6.77s/it]

--- Question ID: 23736032 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        yes

Evaluating RAG Pipelines:  14%|█▍        | 70/500 [07:43<1:02:30,  8.72s/it]

--- Question ID: 28143468 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  15%|█▍        | 73/500 [07:59<51:14,  7.20s/it]

--- Question ID: 18570208 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  15%|█▌        | 75/500 [08:12<49:05,  6.93s/it]

--- Question ID: 22117569 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  15%|█▌        | 76/500 [08:35<1:09:31,  9.84s/it]

--- Question ID: 18783922 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  15%|█▌        | 77/500 [08:55<1:22:35, 11.72s/it]

--- Question ID: 15528969 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  16%|█▌        | 78/500 [09:08<1:24:29, 12.01s/it]

--- Question ID: 19482903 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        yes

Evaluating RAG Pipelines:  17%|█▋        | 86/500 [09:21<31:30,  4.57s/it]

--- Question ID: 16713745 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  17%|█▋        | 87/500 [09:36<40:09,  5.83s/it]

--- Question ID: 21864397 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  18%|█▊        | 89/500 [09:49<41:02,  5.99s/it]

--- Question ID: 11943048 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  18%|█▊        | 90/500 [10:06<51:38,  7.56s/it]

--- Question ID: 23347337 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  18%|█▊        | 91/500 [10:17<55:47,  8.19s/it]

--- Question ID: 23992109 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  19%|█▊        | 93/500 [10:33<55:22,  8.16s/it]

--- Question ID: 26601554 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  19%|█▉        | 94/500 [10:47<1:02:40,  9.26s/it]

--- Question ID: 15489384 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        yes

Evaluating RAG Pipelines:  19%|█▉        | 95/500 [10:59<1:06:48,  9.90s/it]

--- Question ID: 27818079 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  19%|█▉        | 96/500 [11:13<1:13:13, 10.87s/it]

--- Question ID: 24340838 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        yes

Evaluating RAG Pipelines:  19%|█▉        | 97/500 [11:30<1:22:56, 12.35s/it]

--- Question ID: 16971978 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  20%|█▉        | 98/500 [11:43<1:23:12, 12.42s/it]

--- Question ID: 21689015 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        yes

Evaluating RAG Pipelines:  20%|██        | 100/500 [11:52<1:00:50,  9.13s/it]

--- Question ID: 22694248 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        yes
💾 Checkpoint saved at 300 completed questions.

Evaluating RAG Pipelines:  20%|██        | 101/500 [12:03<1:03:52,  9.61s/it]

--- Question ID: 15488260 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    unknown
Semantic RAG:   unknown
CBR RAG:        maybe

Evaluating RAG Pipelines:  21%|██        | 104/500 [12:20<50:16,  7.62s/it]

--- Question ID: 12098035 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  21%|██        | 105/500 [12:36<1:00:13,  9.15s/it]

--- Question ID: 23448747 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  21%|██        | 106/500 [12:49<1:05:24,  9.96s/it]

--- Question ID: 24359102 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  21%|██▏       | 107/500 [12:57<1:03:13,  9.65s/it]

--- Question ID: 14697414 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    unknown
Semantic RAG:   unknown
CBR RAG:        no

Evaluating RAG Pipelines:  23%|██▎       | 114/500 [13:13<28:25,  4.42s/it]

--- Question ID: 22188074 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  24%|██▍       | 119/500 [13:23<21:31,  3.39s/it]

--- Question ID: 9142039 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  24%|██▍       | 121/500 [13:32<23:06,  3.66s/it]

--- Question ID: 24298614 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        maybe

Evaluating RAG Pipelines:  25%|██▌       | 125/500 [13:44<21:16,  3.40s/it]

--- Question ID: 25481573 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  26%|██▌       | 128/500 [13:58<23:08,  3.73s/it]

--- Question ID: 21123461 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   maybe
CBR RAG:        unknown

Evaluating RAG Pipelines:  26%|██▌       | 130/500 [14:11<26:49,  4.35s/it]

--- Question ID: 10548670 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        unknown

Evaluating RAG Pipelines:  26%|██▌       | 131/500 [14:20<30:22,  4.94s/it]

--- Question ID: 21848798 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  26%|██▋       | 132/500 [14:29<33:41,  5.49s/it]

--- Question ID: 25675614 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  27%|██▋       | 133/500 [14:42<42:49,  7.00s/it]

--- Question ID: 25986020 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  27%|██▋       | 134/500 [14:58<53:40,  8.80s/it]

--- Question ID: 18472368 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  28%|██▊       | 140/500 [15:18<31:43,  5.29s/it]

--- Question ID: 24013712 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  28%|██▊       | 142/500 [15:32<34:08,  5.72s/it]

--- Question ID: 27456836 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  29%|██▉       | 144/500 [15:47<36:13,  6.10s/it]

--- Question ID: 22825590 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  29%|██▉       | 145/500 [16:00<42:13,  7.14s/it]

--- Question ID: 23361217 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  29%|██▉       | 146/500 [16:13<48:31,  8.22s/it]

--- Question ID: 18307476 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  29%|██▉       | 147/500 [16:33<1:02:03, 10.55s/it]

--- Question ID: 22237146 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  30%|██▉       | 148/500 [16:52<1:13:35, 12.54s/it]

--- Question ID: 25043083 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  30%|███       | 150/500 [17:09<1:03:37, 10.91s/it]

--- Question ID: 23517744 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  30%|███       | 152/500 [17:25<57:07,  9.85s/it]

--- Question ID: 10749257 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  31%|███       | 154/500 [17:36<48:36,  8.43s/it]

--- Question ID: 15223779 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  31%|███       | 155/500 [17:49<53:13,  9.26s/it]

--- Question ID: 16776337 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  31%|███       | 156/500 [18:07<1:04:19, 11.22s/it]

--- Question ID: 23916653 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  31%|███▏      | 157/500 [18:16<1:01:50, 10.82s/it]

--- Question ID: 10201555 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  32%|███▏      | 159/500 [18:37<1:00:21, 10.62s/it]

--- Question ID: 8910148 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        yes

Evaluating RAG Pipelines:  32%|███▏      | 161/500 [18:52<53:37,  9.49s/it]

--- Question ID: 22617083 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  33%|███▎      | 163/500 [19:04<46:20,  8.25s/it]

--- Question ID: 16465002 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  33%|███▎      | 164/500 [19:20<54:57,  9.81s/it]

--- Question ID: 25940336 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  33%|███▎      | 165/500 [19:37<1:04:01, 11.47s/it]

--- Question ID: 24191126 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  34%|███▎      | 168/500 [19:53<46:23,  8.38s/it]

--- Question ID: 22012962 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  34%|███▍      | 169/500 [20:05<50:06,  9.08s/it]

--- Question ID: 12442934 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  34%|███▍      | 171/500 [20:16<43:29,  7.93s/it]

--- Question ID: 20605051 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  34%|███▍      | 172/500 [20:29<48:22,  8.85s/it]

--- Question ID: 19108857 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  35%|███▌      | 176/500 [20:39<29:34,  5.48s/it]

--- Question ID: 20602784 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  36%|███▌      | 178/500 [20:50<29:38,  5.52s/it]

--- Question ID: 18322741 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  36%|███▌      | 179/500 [21:11<42:54,  8.02s/it]

--- Question ID: 14692023 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  36%|███▌      | 180/500 [21:27<50:38,  9.50s/it]

--- Question ID: 22348433 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  36%|███▌      | 181/500 [21:38<52:07,  9.81s/it]

--- Question ID: 26215326 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  37%|███▋      | 183/500 [21:57<51:03,  9.66s/it]

--- Question ID: 9363244 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  37%|███▋      | 185/500 [22:12<47:26,  9.04s/it]

--- Question ID: 22350859 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        yes

Evaluating RAG Pipelines:  38%|███▊      | 188/500 [22:27<37:53,  7.29s/it]

--- Question ID: 9920954 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    unknown
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  38%|███▊      | 189/500 [22:45<47:23,  9.14s/it]

--- Question ID: 8916748 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  38%|███▊      | 191/500 [22:58<41:59,  8.15s/it]

--- Question ID: 19302863 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  39%|███▊      | 193/500 [23:14<41:27,  8.10s/it]

--- Question ID: 18179827 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  39%|███▉      | 197/500 [23:23<27:07,  5.37s/it]

--- Question ID: 23848044 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  40%|███▉      | 199/500 [23:36<28:37,  5.71s/it]

--- Question ID: 28247485 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   maybe
CBR RAG:        no
💾 Checkpoint saved at 350 completed questions.

Evaluating RAG Pipelines:  40%|████      | 200/500 [23:53<36:52,  7.37s/it]

--- Question ID: 24977765 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  40%|████      | 201/500 [24:16<50:44, 10.18s/it]

--- Question ID: 14551704 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  40%|████      | 202/500 [24:37<1:01:21, 12.35s/it]

--- Question ID: 12632437 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  41%|████      | 204/500 [24:58<57:52, 11.73s/it]

--- Question ID: 17565137 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        maybe

Evaluating RAG Pipelines:  41%|████▏     | 207/500 [25:17<45:37,  9.34s/it]

--- Question ID: 21074975 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  42%|████▏     | 208/500 [25:34<51:31, 10.59s/it]

--- Question ID: 25604390 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  42%|████▏     | 209/500 [25:48<55:15, 11.39s/it]

--- Question ID: 14968373 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  42%|████▏     | 210/500 [26:03<58:08, 12.03s/it]

--- Question ID: 10135926 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        yes

Evaluating RAG Pipelines:  42%|████▏     | 211/500 [26:20<1:04:22, 13.37s/it]

--- Question ID: 19419587 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  42%|████▏     | 212/500 [26:33<1:03:46, 13.29s/it]

--- Question ID: 23379759 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  43%|████▎     | 213/500 [26:46<1:03:07, 13.20s/it]

--- Question ID: 19923859 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  43%|████▎     | 214/500 [27:04<1:09:01, 14.48s/it]

--- Question ID: 22656647 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  43%|████▎     | 216/500 [27:20<54:59, 11.62s/it]

--- Question ID: 21658267 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  44%|████▎     | 218/500 [27:37<48:42, 10.36s/it]

--- Question ID: 23375036 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  44%|████▍     | 219/500 [27:52<53:15, 11.37s/it]

--- Question ID: 24495711 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  44%|████▍     | 221/500 [28:16<54:06, 11.63s/it]

--- Question ID: 26516021 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  44%|████▍     | 222/500 [28:39<1:05:06, 14.05s/it]

--- Question ID: 20064872 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    maybe
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  45%|████▍     | 224/500 [28:53<52:53, 11.50s/it]

--- Question ID: 29112560 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  45%|████▌     | 227/500 [29:07<38:20,  8.43s/it]

--- Question ID: 23870157 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  46%|████▌     | 228/500 [29:22<42:50,  9.45s/it]

--- Question ID: 18540901 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  46%|████▌     | 229/500 [29:32<43:11,  9.56s/it]

--- Question ID: 21420186 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    unknown
Semantic RAG:   unknown
CBR RAG:        no

Evaluating RAG Pipelines:  46%|████▌     | 231/500 [29:46<38:36,  8.61s/it]

--- Question ID: 23321509 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  47%|████▋     | 234/500 [30:01<31:19,  7.06s/it]

--- Question ID: 25521278 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  48%|████▊     | 238/500 [30:18<25:30,  5.84s/it]

--- Question ID: 10490564 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  48%|████▊     | 239/500 [30:36<32:38,  7.50s/it]

--- Question ID: 7860319 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        unknown

Evaluating RAG Pipelines:  48%|████▊     | 241/500 [30:50<31:40,  7.34s/it]

--- Question ID: 9488747 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  48%|████▊     | 242/500 [31:00<33:46,  7.85s/it]

--- Question ID: 20354380 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  49%|████▊     | 243/500 [31:18<41:50,  9.77s/it]

--- Question ID: 24245816 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  49%|████▉     | 245/500 [31:34<38:38,  9.09s/it]

--- Question ID: 27217036 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        unknown

Evaluating RAG Pipelines:  49%|████▉     | 246/500 [31:54<47:50, 11.30s/it]

--- Question ID: 23283159 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  49%|████▉     | 247/500 [32:04<46:48, 11.10s/it]

--- Question ID: 19593710 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  50%|████▉     | 248/500 [32:21<52:48, 12.57s/it]

--- Question ID: 18693227 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  50%|█████     | 250/500 [32:35<42:59, 10.32s/it]

--- Question ID: 17910536 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  50%|█████     | 252/500 [32:46<34:44,  8.41s/it]

--- Question ID: 18616781 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    unknown
Semantic RAG:   unknown
CBR RAG:        maybe

Evaluating RAG Pipelines:  51%|█████     | 254/500 [33:01<33:06,  8.08s/it]

--- Question ID: 12848629 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  51%|█████     | 255/500 [33:13<36:19,  8.89s/it]

--- Question ID: 25280365 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  52%|█████▏    | 258/500 [33:25<27:09,  6.73s/it]

--- Question ID: 26418441 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  52%|█████▏    | 262/500 [33:42<22:04,  5.57s/it]

--- Question ID: 18222909 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  53%|█████▎    | 263/500 [33:57<27:06,  6.86s/it]

--- Question ID: 12221908 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        yes

Evaluating RAG Pipelines:  53%|█████▎    | 264/500 [34:07<29:00,  7.37s/it]

--- Question ID: 24014276 ---
Ground Truth:   yes
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  53%|█████▎    | 267/500 [34:22<24:51,  6.40s/it]

--- Question ID: 16772913 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  54%|█████▎    | 268/500 [34:34<28:37,  7.40s/it]

--- Question ID: 12172698 ---
Ground Truth:   yes
No RAG Output:  no
Keyword RAG:    maybe
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  54%|█████▍    | 270/500 [34:48<27:37,  7.21s/it]

--- Question ID: 12419743 ---
Ground Truth:   yes
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  56%|█████▌    | 278/500 [35:11<16:10,  4.37s/it]

--- Question ID: 24669960 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        unknown

Evaluating RAG Pipelines:  56%|█████▌    | 279/500 [35:30<21:51,  5.93s/it]

--- Question ID: 15502995 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   no
CBR RAG:        yes

Evaluating RAG Pipelines:  56%|█████▌    | 281/500 [35:44<22:20,  6.12s/it]

--- Question ID: 24476003 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  57%|█████▋    | 285/500 [35:59<18:38,  5.20s/it]

--- Question ID: 18496363 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  57%|█████▋    | 287/500 [36:12<19:44,  5.56s/it]

--- Question ID: 14631523 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  58%|█████▊    | 289/500 [36:25<20:21,  5.79s/it]

--- Question ID: 17971187 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  58%|█████▊    | 290/500 [36:41<25:08,  7.18s/it]

--- Question ID: 27642458 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no
💾 Checkpoint saved at 400 completed questions.

Evaluating RAG Pipelines:  58%|█████▊    | 292/500 [36:57<26:04,  7.52s/it]

--- Question ID: 11138995 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        unknown

Evaluating RAG Pipelines:  59%|█████▊    | 293/500 [37:13<30:34,  8.86s/it]

--- Question ID: 15388567 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  59%|█████▉    | 294/500 [37:26<33:43,  9.82s/it]

--- Question ID: 19142546 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        no

Evaluating RAG Pipelines:  59%|█████▉    | 297/500 [37:38<23:51,  7.05s/it]

--- Question ID: 22668852 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  60%|█████▉    | 298/500 [37:50<27:03,  8.04s/it]

--- Question ID: 18019905 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  60%|██████    | 301/500 [38:03<21:02,  6.34s/it]

--- Question ID: 7547656 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  61%|██████    | 304/500 [38:25<21:56,  6.72s/it]

--- Question ID: 10781708 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   maybe
CBR RAG:        unknown

Evaluating RAG Pipelines:  61%|██████    | 305/500 [38:43<27:27,  8.45s/it]

--- Question ID: 22522271 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        unknown

Evaluating RAG Pipelines:  62%|██████▏   | 308/500 [39:04<25:17,  7.90s/it]

--- Question ID: 27338535 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  63%|██████▎   | 314/500 [39:21<16:03,  5.18s/it]

--- Question ID: 8199520 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  63%|██████▎   | 315/500 [39:37<19:51,  6.44s/it]

--- Question ID: 21889895 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        yes

Evaluating RAG Pipelines:  63%|██████▎   | 316/500 [39:57<25:21,  8.27s/it]

--- Question ID: 26113007 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   maybe
CBR RAG:        unknown

Evaluating RAG Pipelines:  64%|██████▎   | 318/500 [40:13<24:54,  8.21s/it]

--- Question ID: 20538207 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  64%|██████▍   | 319/500 [40:29<28:55,  9.59s/it]

--- Question ID: 9603166 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  64%|██████▍   | 321/500 [40:41<25:12,  8.45s/it]

--- Question ID: 21252642 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  65%|██████▍   | 323/500 [40:58<24:47,  8.40s/it]

--- Question ID: 20549895 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        no

Evaluating RAG Pipelines:  65%|██████▍   | 324/500 [41:12<27:38,  9.42s/it]

--- Question ID: 16418930 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  65%|██████▌   | 325/500 [41:32<33:57, 11.65s/it]

--- Question ID: 8521557 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  65%|██████▌   | 327/500 [41:47<29:22, 10.19s/it]

--- Question ID: 10798511 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  67%|██████▋   | 334/500 [42:03<13:53,  5.02s/it]

--- Question ID: 19398929 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  67%|██████▋   | 335/500 [42:16<16:12,  5.89s/it]

--- Question ID: 25614468 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  67%|██████▋   | 337/500 [42:35<18:31,  6.82s/it]

--- Question ID: 10973547 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  68%|██████▊   | 340/500 [42:48<15:46,  5.92s/it]

--- Question ID: 23677366 ---
Ground Truth:   no
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        maybe

Evaluating RAG Pipelines:  68%|██████▊   | 341/500 [43:04<19:49,  7.48s/it]

--- Question ID: 17342562 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   maybe
CBR RAG:        unknown

Evaluating RAG Pipelines:  68%|██████▊   | 342/500 [43:18<22:31,  8.55s/it]

--- Question ID: 16296668 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  69%|██████▉   | 346/500 [43:40<17:53,  6.97s/it]

--- Question ID: 22513023 ---
Ground Truth:   no
No RAG Output:  no
Keyword RAG:    no
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  70%|██████▉   | 349/500 [43:56<16:16,  6.46s/it]

--- Question ID: 12006913 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  70%|███████   | 352/500 [44:13<15:16,  6.19s/it]

--- Question ID: 22154448 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        unknown

Evaluating RAG Pipelines:  71%|███████   | 354/500 [44:28<15:57,  6.56s/it]

--- Question ID: 22365295 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  72%|███████▏  | 359/500 [44:41<10:56,  4.66s/it]

--- Question ID: 21946341 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    unknown
Semantic RAG:   unknown
CBR RAG:        maybe

Evaluating RAG Pipelines:  72%|███████▏  | 362/500 [44:54<10:35,  4.60s/it]

--- Question ID: 22534881 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  73%|███████▎  | 363/500 [45:13<14:27,  6.34s/it]

--- Question ID: 8566975 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        unknown

Evaluating RAG Pipelines:  73%|███████▎  | 365/500 [45:23<13:26,  5.97s/it]

--- Question ID: 22668712 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  74%|███████▍  | 369/500 [45:45<12:30,  5.73s/it]

--- Question ID: 18359123 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   maybe
CBR RAG:        unknown

Evaluating RAG Pipelines:  74%|███████▍  | 370/500 [46:03<15:52,  7.33s/it]

--- Question ID: 16827975 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        unknown

Evaluating RAG Pipelines:  74%|███████▍  | 371/500 [46:12<16:22,  7.62s/it]

--- Question ID: 24922528 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  74%|███████▍  | 372/500 [46:28<19:32,  9.16s/it]

--- Question ID: 15774570 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   maybe
CBR RAG:        yes

Evaluating RAG Pipelines:  75%|███████▌  | 375/500 [46:41<14:40,  7.04s/it]

--- Question ID: 9542484 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  76%|███████▌  | 379/500 [46:57<11:23,  5.65s/it]

--- Question ID: 22537902 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        unknown

Evaluating RAG Pipelines:  77%|███████▋  | 384/500 [47:08<08:01,  4.15s/it]

--- Question ID: 25752912 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  77%|███████▋  | 385/500 [47:23<10:10,  5.31s/it]

--- Question ID: 26536001 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  77%|███████▋  | 386/500 [47:44<14:19,  7.54s/it]

--- Question ID: 21849531 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  78%|███████▊  | 388/500 [47:58<13:42,  7.35s/it]

--- Question ID: 23571528 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  78%|███████▊  | 390/500 [48:10<12:50,  7.00s/it]

--- Question ID: 23621776 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  78%|███████▊  | 392/500 [48:24<12:41,  7.05s/it]

--- Question ID: 23025584 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  79%|███████▊  | 393/500 [48:37<14:25,  8.09s/it]

--- Question ID: 11862129 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  79%|███████▉  | 394/500 [48:52<16:43,  9.46s/it]

--- Question ID: 22236315 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  79%|███████▉  | 395/500 [49:04<17:31, 10.02s/it]

--- Question ID: 21361755 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  79%|███████▉  | 397/500 [49:15<14:00,  8.16s/it]

--- Question ID: 11438275 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  80%|███████▉  | 398/500 [49:34<18:05, 10.64s/it]

--- Question ID: 16778275 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no
💾 Checkpoint saved at 450 completed questions.

Evaluating RAG Pipelines:  80%|███████▉  | 399/500 [49:48<19:01, 11.30s/it]

--- Question ID: 17051586 ---
Ground Truth:   no
No RAG Output:  no
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  80%|████████  | 402/500 [50:08<14:49,  9.07s/it]

--- Question ID: 23497210 ---
Ground Truth:   no
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  81%|████████  | 403/500 [50:23<16:29, 10.21s/it]

--- Question ID: 25488308 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  81%|████████  | 404/500 [50:40<18:40, 11.67s/it]

--- Question ID: 22382608 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  81%|████████▏ | 407/500 [51:06<15:43, 10.15s/it]

--- Question ID: 9100537 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  82%|████████▏ | 408/500 [51:29<19:16, 12.57s/it]

--- Question ID: 23422012 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  82%|████████▏ | 409/500 [51:46<20:30, 13.52s/it]

--- Question ID: 22876568 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   maybe
CBR RAG:        yes

Evaluating RAG Pipelines:  82%|████████▏ | 411/500 [51:59<16:06, 10.86s/it]

--- Question ID: 20608141 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  83%|████████▎ | 416/500 [52:12<08:37,  6.16s/it]

--- Question ID: 23794696 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        no

Evaluating RAG Pipelines:  83%|████████▎ | 417/500 [52:25<09:49,  7.10s/it]

--- Question ID: 23076787 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  84%|████████▍ | 419/500 [52:36<08:58,  6.65s/it]

--- Question ID: 14652839 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  84%|████████▍ | 420/500 [52:48<09:59,  7.50s/it]

--- Question ID: 7664228 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  84%|████████▍ | 421/500 [53:02<11:41,  8.88s/it]

--- Question ID: 17062234 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  85%|████████▍ | 423/500 [53:25<12:31,  9.76s/it]

--- Question ID: 12070552 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  85%|████████▌ | 426/500 [53:37<08:55,  7.23s/it]

--- Question ID: 24739448 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   yes
CBR RAG:        no

Evaluating RAG Pipelines:  85%|████████▌ | 427/500 [53:52<10:20,  8.51s/it]

--- Question ID: 24625433 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  86%|████████▌ | 429/500 [54:08<09:51,  8.34s/it]

--- Question ID: 10375486 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  87%|████████▋ | 433/500 [54:21<06:41,  5.99s/it]

--- Question ID: 17274051 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  87%|████████▋ | 435/500 [54:31<06:10,  5.70s/it]

--- Question ID: 7497757 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  87%|████████▋ | 436/500 [55:23<13:45, 12.90s/it]

--- Question ID: 21459725 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  88%|████████▊ | 438/500 [55:36<11:16, 10.91s/it]

--- Question ID: 20187289 ---
Ground Truth:   no
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  88%|████████▊ | 440/500 [55:50<09:38,  9.65s/it]

--- Question ID: 10456814 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        yes

Evaluating RAG Pipelines:  89%|████████▊ | 443/500 [56:10<08:07,  8.55s/it]

--- Question ID: 12769830 ---
Ground Truth:   no
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   maybe
CBR RAG:        unknown

Evaluating RAG Pipelines:  89%|████████▉ | 444/500 [56:29<09:27, 10.13s/it]

--- Question ID: 22251324 ---
Ground Truth:   no
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  89%|████████▉ | 447/500 [56:46<07:23,  8.36s/it]

--- Question ID: 18802997 ---
Ground Truth:   maybe
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        maybe

Evaluating RAG Pipelines:  90%|████████▉ | 449/500 [57:01<06:52,  8.09s/it]

--- Question ID: 11411430 ---
Ground Truth:   maybe
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  90%|█████████ | 450/500 [57:19<08:05,  9.71s/it]

--- Question ID: 26708803 ---
Ground Truth:   maybe
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        yes

Evaluating RAG Pipelines:  90%|█████████ | 451/500 [57:30<08:12, 10.04s/it]

--- Question ID: 25079920 ---
Ground Truth:   maybe
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  91%|█████████ | 453/500 [57:54<08:24, 10.73s/it]

--- Question ID: 19103915 ---
Ground Truth:   maybe
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  91%|█████████ | 454/500 [58:12<09:16, 12.10s/it]

--- Question ID: 11867487 ---
Ground Truth:   maybe
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  92%|█████████▏| 458/500 [58:28<05:28,  7.81s/it]

--- Question ID: 20971618 ---
Ground Truth:   maybe
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  92%|█████████▏| 461/500 [58:52<05:05,  7.84s/it]

--- Question ID: 16968876 ---
Ground Truth:   maybe
No RAG Output:  no
Keyword RAG:    no
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  93%|█████████▎| 463/500 [59:03<04:30,  7.30s/it]

--- Question ID: 18568290 ---
Ground Truth:   maybe
No RAG Output:  unknown
Keyword RAG:    unknown
Semantic RAG:   unknown
CBR RAG:        maybe

Evaluating RAG Pipelines:  93%|█████████▎| 466/500 [59:16<03:31,  6.21s/it]

--- Question ID: 11570976 ---
Ground Truth:   maybe
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  93%|█████████▎| 467/500 [59:29<03:58,  7.23s/it]

--- Question ID: 16816043 ---
Ground Truth:   maybe
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  94%|█████████▍| 469/500 [59:42<03:34,  6.93s/it]

--- Question ID: 25571931 ---
Ground Truth:   maybe
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  94%|█████████▍| 470/500 [59:52<03:45,  7.53s/it]

--- Question ID: 19578820 ---
Ground Truth:   maybe
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines:  94%|█████████▍| 472/500 [1:00:05<03:22,  7.23s/it]

--- Question ID: 11458136 ---
Ground Truth:   maybe
No RAG Output:  unknown
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  95%|█████████▍| 473/500 [1:00:12<03:13,  7.16s/it]

--- Question ID: 12790890 ---
Ground Truth:   maybe
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        maybe

Evaluating RAG Pipelines:  95%|█████████▌| 476/500 [1:00:25<02:21,  5.89s/it]

--- Question ID: 24995509 ---
Ground Truth:   maybe
No RAG Output:  no
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        maybe

Evaluating RAG Pipelines:  95%|█████████▌| 477/500 [1:00:39<02:46,  7.24s/it]

--- Question ID: 27044366 ---
Ground Truth:   maybe
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  96%|█████████▌| 478/500 [1:00:55<03:19,  9.08s/it]

--- Question ID: 26606599 ---
Ground Truth:   maybe
No RAG Output:  no
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  96%|█████████▌| 480/500 [1:01:05<02:30,  7.53s/it]

--- Question ID: 26037986 ---
Ground Truth:   maybe
No RAG Output:  yes
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  96%|█████████▋| 482/500 [1:01:23<02:25,  8.08s/it]

--- Question ID: 24591144 ---
Ground Truth:   maybe
No RAG Output:  unknown
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        unknown

Evaluating RAG Pipelines:  97%|█████████▋| 486/500 [1:01:31<01:10,  5.02s/it]

--- Question ID: 18235194 ---
Ground Truth:   maybe
No RAG Output:  maybe
Keyword RAG:    no
Semantic RAG:   no
CBR RAG:        no

Evaluating RAG Pipelines:  98%|█████████▊| 489/500 [1:01:49<01:00,  5.47s/it]

--- Question ID: 27615402 ---
Ground Truth:   maybe
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        unknown

Evaluating RAG Pipelines:  98%|█████████▊| 490/500 [1:02:06<01:09,  6.97s/it]

--- Question ID: 25779009 ---
Ground Truth:   maybe
No RAG Output:  maybe
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  99%|█████████▉| 494/500 [1:02:17<00:30,  5.16s/it]

--- Question ID: 20736672 ---
Ground Truth:   maybe
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes

Evaluating RAG Pipelines:  99%|█████████▉| 496/500 [1:02:40<00:26,  6.64s/it]

--- Question ID: 17691856 ---
Ground Truth:   maybe
No RAG Output:  maybe
Keyword RAG:    maybe
Semantic RAG:   maybe
CBR RAG:        no

Evaluating RAG Pipelines: 100%|██████████| 500/500 [1:02:51<00:00,  7.54s/it]

--- Question ID: 19694846 ---
Ground Truth:   maybe
No RAG Output:  unknown
Keyword RAG:    yes
Semantic RAG:   yes
CBR RAG:        yes
💾 Checkpoint saved at 500 completed questions.

✅ Final checkpoint saved: /content/drive/MyDrive/rag_checkpoint_cbr500.csv
Total prediction rows: 2000
Total question IDs completed: 500

In [ ]:
# =========================
# CLASSIFICATION METRICS
# =========================

pred_df = pd.read_csv(CHECKPOINT_PATH)

# Convert retrieved_pmids from string to list
pred_df["retrieved_pmids"] = pred_df["retrieved_pmids"].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) and x.startswith("[") else []
)

summary_rows = []

for method in sorted(pred_df["method"].unique()):
    sub = pred_df[pred_df["method"] == method].copy()

    valid = sub[
        sub["gold"].isin(LABELS) &
        sub["pred"].isin(LABELS)
    ].copy()

    if len(valid) == 0:
        continue

    summary_rows.append({
        "Method": method,
        "Accuracy": accuracy_score(valid["gold"], valid["pred"]),
        "Macro F1": f1_score(valid["gold"], valid["pred"], average="macro"),
        "Macro Precision": precision_score(valid["gold"], valid["pred"], average="macro", zero_division=0),
        "Macro Recall": recall_score(valid["gold"], valid["pred"], average="macro", zero_division=0),
        "Valid N": len(valid),
        "Unknown/Invalid Outputs": len(sub) - len(valid),
    })

summary_df = pd.DataFrame(summary_rows)
display(summary_df)

,Method,Accuracy,Macro F1,Macro Precision,Macro Recall,Valid N,Unknown/Invalid Outputs
0,cbr_rag,0.597590,0.485290,0.490901,0.488334,415,85
1,keyword_rag,0.496868,0.432829,0.474942,0.435167,479,21
2,no_rag,0.154519,0.147405,0.332658,0.333185,343,157
3,semantic_rag,0.494824,0.423593,0.476904,0.419017,483,17

In [ ]:
# =========================
# CLASSIFICATION REPORTS + CONFUSION MATRICES
# =========================

for method in sorted(pred_df["method"].unique()):
    sub = pred_df[pred_df["method"] == method].copy()

    valid = sub[
        sub["gold"].isin(LABELS) &
        sub["pred"].isin(LABELS)
    ].copy()

    if len(valid) == 0:
        print(f"\n{method.upper()}: No valid predictions")
        continue

    print("\n" + "=" * 80)
    print(method.upper())
    print("=" * 80)

    print(classification_report(
        valid["gold"],
        valid["pred"],
        labels=LABELS,
        zero_division=0
    ))

    cm = confusion_matrix(
        valid["gold"],
        valid["pred"],
        labels=LABELS
    )

    cm_df = pd.DataFrame(
        cm,
        index=[f"true_{l}" for l in LABELS],
        columns=[f"pred_{l}" for l in LABELS]
    )

    display(cm_df)

================================================================================
CBR_RAG
================================================================================
              precision    recall  f1-score   support

         yes       0.75      0.64      0.69       231
          no       0.61      0.66      0.64       142
       maybe       0.10      0.17      0.13        42

    accuracy                           0.60       415
   macro avg       0.49      0.49      0.49       415
weighted avg       0.64      0.60      0.62       415

            pred_yes  pred_no  pred_maybe
true_yes         147       43          41
true_no           29       94          19
true_maybe        19       16           7

================================================================================
KEYWORD_RAG
================================================================================
              precision    recall  f1-score   support

         yes       0.70      0.58      0.63       261
          no       0.62      0.43      0.51       164
       maybe       0.11      0.30      0.16        54

    accuracy                           0.50       479
   macro avg       0.47      0.44      0.43       479
weighted avg       0.60      0.50      0.54       479

            pred_yes  pred_no  pred_maybe
true_yes         152       31          78
true_no           40       70          54
true_maybe        26       12          16

================================================================================
NO_RAG
================================================================================
              precision    recall  f1-score   support

         yes       0.60      0.02      0.03       192
          no       0.28      0.17      0.21       113
       maybe       0.11      0.82      0.20        38

    accuracy                           0.15       343
   macro avg       0.33      0.33      0.15       343
weighted avg       0.44      0.15      0.11       343

            pred_yes  pred_no  pred_maybe
true_yes           3       42         147
true_no            1       19          93
true_maybe         1        6          31

================================================================================
SEMANTIC_RAG
================================================================================
              precision    recall  f1-score   support

         yes       0.71      0.61      0.65       265
          no       0.63      0.39      0.48       164
       maybe       0.09      0.26      0.13        54

    accuracy                           0.49       483
   macro avg       0.48      0.42      0.42       483
weighted avg       0.61      0.49      0.54       483

            pred_yes  pred_no  pred_maybe
true_yes         161       25          79
true_no           39       64          61
true_maybe        28       12          14

In [ ]:
# =========================
# RETRIEVAL METRICS: HIT@K / RECALL@K
# =========================

def hit_at_k(qid, retrieved_pmids, k):
    retrieved_pmids = [str(x) for x in retrieved_pmids[:k]]
    return str(qid) in retrieved_pmids

def reciprocal_rank(qid, retrieved_pmids):
    qid = str(qid)
    retrieved_pmids = [str(x) for x in retrieved_pmids]
    for rank, pmid in enumerate(retrieved_pmids, start=1):
        if pmid == qid:
            return 1.0 / rank

    return 0.0

rag_methods = ["keyword_rag", "semantic_rag", "graph_rag", "cbr_rag"]
retrieval_rows = []
for method in rag_methods:
    sub = pred_df[pred_df["method"] == method].copy()
    if len(sub) == 0:
        continue
    row = {"Method": method}
    row["MRR"] = sub.apply(
        lambda r: reciprocal_rank(r["qid"], r["retrieved_pmids"]),
        axis=1
    ).mean()

    for k in [1, 3, 5, 10]:
        row[f"Hit@{k}"] = sub.apply(
            lambda r: hit_at_k(r["qid"], r["retrieved_pmids"], k),
            axis=1
        ).mean()
    retrieval_rows.append(row)

retrieval_summary_df = pd.DataFrame(retrieval_rows)

display(retrieval_summary_df)

         Method       MRR  Hit@1  Hit@3  Hit@5  Hit@10
0   keyword_rag  0.554633  0.488  0.602  0.660   0.670
1  semantic_rag  0.736733  0.714  0.756  0.766   0.766
2       cbr_rag  0.736733  0.714  0.756  0.766   0.766

In [ ]:
# =========================
# COMBINED FINAL RESULTS TABLE
# =========================

combined_results = summary_df.merge(
    retrieval_summary_df,
    on="Method",
    how="left"
)

display(combined_results)

,Method,Accuracy,Macro F1,Macro Precision,Macro Recall,Valid N,Unknown/Invalid Outputs,MRR,Hit@1,Hit@3,Hit@5,Hit@10
0,cbr_rag,0.597590,0.485290,0.490901,0.488334,415,85,0.736733,0.714,0.756,0.766,0.766
1,keyword_rag,0.496868,0.432829,0.474942,0.435167,479,21,0.554633,0.488,0.602,0.660,0.670
2,no_rag,0.154519,0.147405,0.332658,0.333185,343,157,NaN,NaN,NaN,NaN,NaN
3,semantic_rag,0.494824,0.423593,0.476904,0.419017,483,17,0.736733,0.714,0.756,0.766,0.766

Error Analysis

In [ ]:
# =========================
# ERROR ANALYSIS
# =========================

import ast
import pandas as pd

LABELS = ["yes", "no", "maybe"]

# Safety: convert retrieved_pmids from string to list if needed
def parse_pmids(x):
    if isinstance(x, list):
        return x
    if isinstance(x, str) and x.startswith("["):
        try:
            return ast.literal_eval(x)
        except Exception:
            return []
    return []

pred_df["retrieved_pmids"] = pred_df["retrieved_pmids"].apply(parse_pmids)


# -------------------------
# Helper functions
# -------------------------
def gold_in_retrieved(row, k=None):
    retrieved = row["retrieved_pmids"]
    if k is not None:
        retrieved = retrieved[:k]

    retrieved = [str(x) for x in retrieved]
    return str(row["qid"]) in retrieved


def classify_error(row):
    gold = row["gold"]
    pred = row["pred"]

    # No-RAG has no retrieval step
    if row["method"] == "no_rag":
        if gold == pred:
            return "correct"
        elif pred not in LABELS:
            return "invalid_output"
        else:
            return "model_error_no_rag"

    # RAG methods
    if gold == pred:
        return "correct"

    if pred not in LABELS:
        return "invalid_output"

    if not gold_in_retrieved(row, k=None):
        return "retrieval_failure"

    return "generation_failure"


# -------------------------
# Add analysis columns
# -------------------------
pred_df["is_correct"] = pred_df["gold"] == pred_df["pred"]
pred_df["gold_in_top1"] = pred_df.apply(lambda r: gold_in_retrieved(r, k=1), axis=1)
pred_df["gold_in_top3"] = pred_df.apply(lambda r: gold_in_retrieved(r, k=3), axis=1)
pred_df["gold_in_top5"] = pred_df.apply(lambda r: gold_in_retrieved(r, k=5), axis=1)
pred_df["gold_in_top10"] = pred_df.apply(lambda r: gold_in_retrieved(r, k=10), axis=1)
pred_df["error_type"] = pred_df.apply(classify_error, axis=1)

display(pred_df.head())

,qid,method,question,gold,pred,retrieved_pmids,error,is_correct,gold_in_top1,gold_in_top3,gold_in_top5,gold_in_top10,error_type
0,10834864,no_rag,Risk factors for avascular necrosis of bone in...,no,unknown,[],NaN,False,False,False,False,False,invalid_output
1,10834864,keyword_rag,Risk factors for avascular necrosis of bone in...,no,unknown,[],NaN,False,False,False,False,False,invalid_output
2,10834864,semantic_rag,Risk factors for avascular necrosis of bone in...,no,unknown,[],NaN,False,False,False,False,False,invalid_output
3,10834864,cbr_rag,Risk factors for avascular necrosis of bone in...,no,maybe,[],NaN,False,False,False,False,False,retrieval_failure
4,11079675,no_rag,Pulmonary valve replacement in adults late aft...,yes,maybe,[],NaN,False,False,False,False,False,model_error_no_rag

In [ ]:
# =========================
# ERROR TYPE SUMMARY
# =========================

error_summary = (
    pred_df
    .groupby(["method", "error_type"])
    .size()
    .reset_index(name="count")
)

display(error_summary)

# Pivoted version: better for report/presentation
error_pivot = (
    error_summary
    .pivot(index="method", columns="error_type", values="count")
    .fillna(0)
    .astype(int)
    .reset_index()
)

display(error_pivot)

          method          error_type  count
0        cbr_rag             correct    248
1        cbr_rag  generation_failure     99
2        cbr_rag      invalid_output     85
3        cbr_rag   retrieval_failure     68
4    keyword_rag             correct    238
5    keyword_rag  generation_failure    147
6    keyword_rag      invalid_output     21
7    keyword_rag   retrieval_failure     94
8         no_rag             correct     53
9         no_rag      invalid_output    157
10        no_rag  model_error_no_rag    290
11  semantic_rag             correct    239
12  semantic_rag  generation_failure    169
13  semantic_rag      invalid_output     17
14  semantic_rag   retrieval_failure     75

error_type,method,correct,generation_failure,invalid_output,model_error_no_rag,retrieval_failure
0,cbr_rag,248,99,85,0,68
1,keyword_rag,238,147,21,0,94
2,no_rag,53,0,157,290,0
3,semantic_rag,239,169,17,0,75

In [ ]:
# =========================
# ERROR TYPE PERCENTAGES
# =========================

error_percent = error_pivot.copy()

count_cols = [c for c in error_percent.columns if c != "method"]
error_percent["total"] = error_percent[count_cols].sum(axis=1)

for col in count_cols:
    error_percent[col + "_pct"] = error_percent[col] / error_percent["total"]

display(error_percent)

error_type,method,correct,generation_failure,invalid_output,model_error_no_rag,retrieval_failure,total,correct_pct,generation_failure_pct,invalid_output_pct,model_error_no_rag_pct,retrieval_failure_pct
0,cbr_rag,248,99,85,0,68,500,0.496,0.198,0.170,0.00,0.136
1,keyword_rag,238,147,21,0,94,500,0.476,0.294,0.042,0.00,0.188
2,no_rag,53,0,157,290,0,500,0.106,0.000,0.314,0.58,0.000
3,semantic_rag,239,169,17,0,75,500,0.478,0.338,0.034,0.00,0.150

In [ ]:
# =========================
# SHOW RETRIEVAL FAILURES
# =========================

def show_retrieval_failures(method="semantic_rag", n=5):
    sub = pred_df[
        (pred_df["method"] == method) &
        (pred_df["error_type"] == "retrieval_failure")
    ].copy()

    print(f"{method}: {len(sub)} retrieval failures")

    for _, row in sub.head(n).iterrows():
        print("\n" + "=" * 100)
        print("QID / Gold PMID:", row["qid"])
        print("Question:", row["question"])
        print("Gold:", row["gold"])
        print("Pred:", row["pred"])
        print("Retrieved PMIDs:", row["retrieved_pmids"])
        print("Gold in Top 1:", row["gold_in_top1"])
        print("Gold in Top 3:", row["gold_in_top3"])
        print("Gold in Top 5:", row["gold_in_top5"])

show_retrieval_failures("semantic_rag", n=5)

semantic_rag: 75 retrieval failures

====================================================================================================
QID / Gold PMID: 12121321
Question: Do mossy fibers release GABA?
Gold: yes
Pred: maybe
Retrieved PMIDs: ['23365214', '22915124', '23316138', '22842523', '24319410', '22711957']
Gold in Top 1: False
Gold in Top 3: False
Gold in Top 5: False

====================================================================================================
QID / Gold PMID: 20084845
Question: Biomolecular identification of allergenic pollen: a new perspective for aerobiological monitoring?
Gold: yes
Pred: maybe
Retrieved PMIDs: []
Gold in Top 1: False
Gold in Top 3: False
Gold in Top 5: False

====================================================================================================
QID / Gold PMID: 23690198
Question: Implementation of epidural analgesia for labor: is the standard of effective analgesia reachable in all women?
Gold: yes
Pred: maybe
Retrieved PMIDs: []
Gold in Top 1: False
Gold in Top 3: False
Gold in Top 5: False

====================================================================================================
QID / Gold PMID: 12163782
Question: Increased neutrophil migratory activity after major trauma: a factor in the etiology of acute respiratory distress syndrome?
Gold: yes
Pred: maybe
Retrieved PMIDs: []
Gold in Top 1: False
Gold in Top 3: False
Gold in Top 5: False

====================================================================================================
QID / Gold PMID: 27394685
Question: Bony defects in chronic anterior posttraumatic dislocation of the shoulder: Is there a correlation between humeral and glenoidal lesions?
Gold: no
Pred: maybe
Retrieved PMIDs: []
Gold in Top 1: False
Gold in Top 3: False
Gold in Top 5: False

In [ ]:
# =========================
# SHOW GENERATION FAILURES
# =========================

def show_generation_failures(method="semantic_rag", n=5):
    sub = pred_df[
        (pred_df["method"] == method) &
        (pred_df["error_type"] == "generation_failure")
    ].copy()

    print(f"{method}: {len(sub)} generation failures")

    for _, row in sub.head(n).iterrows():
        print("\n" + "=" * 100)
        print("QID / Gold PMID:", row["qid"])
        print("Question:", row["question"])
        print("Gold:", row["gold"])
        print("Pred:", row["pred"])
        print("Retrieved PMIDs:", row["retrieved_pmids"])
        print("Gold in Top 1:", row["gold_in_top1"])
        print("Gold in Top 3:", row["gold_in_top3"])
        print("Gold in Top 5:", row["gold_in_top5"])

show_generation_failures("semantic_rag", n=5)

semantic_rag: 169 generation failures

====================================================================================================
QID / Gold PMID: 11079675
Question: Pulmonary valve replacement in adults late after repair of tetralogy of fallot: are we operating too late?
Gold: yes
Pred: maybe
Retrieved PMIDs: ['11079675', '4010322', '18290882']
Gold in Top 1: True
Gold in Top 3: True
Gold in Top 5: True

====================================================================================================
QID / Gold PMID: 18926458
Question: Are octogenarians at high risk for carotid endarterectomy?
Gold: no
Pred: maybe
Retrieved PMIDs: ['18926458', '19823705', '18091703', '25499530', '15768004', '27625000']
Gold in Top 1: True
Gold in Top 3: True
Gold in Top 5: True

====================================================================================================
QID / Gold PMID: 15943725
Question: Should serum pancreatic lipase replace serum amylase as a biomarker of acute pancreatitis?
Gold: yes
Pred: maybe
Retrieved PMIDs: ['15943725']
Gold in Top 1: True
Gold in Top 3: True
Gold in Top 5: True

====================================================================================================
QID / Gold PMID: 16735905
Question: Does the severity of obstructive sleep apnea predict patients requiring high continuous positive airway pressure?
Gold: maybe
Pred: yes
Retrieved PMIDs: ['16735905', '8503565', '29067558', '28419320', '31421094', '36968331']
Gold in Top 1: True
Gold in Top 3: True
Gold in Top 5: True

====================================================================================================
QID / Gold PMID: 16538201
Question: Does use of hydrophilic guidewires significantly improve technical success rates of peripheral PTA?
Gold: maybe
Pred: yes
Retrieved PMIDs: ['16538201', '7879963', '12236018']
Gold in Top 1: True
Gold in Top 3: True
Gold in Top 5: True

In [ ]:
# =========================
# CASES WHERE RAG HELPED
# =========================

def show_rag_helped(rag_method="semantic_rag", n=5):
    no_rag = pred_df[pred_df["method"] == "no_rag"][["qid", "pred"]].rename(
        columns={"pred": "no_rag_pred"}
    )

    rag = pred_df[pred_df["method"] == rag_method].copy()

    merged = rag.merge(no_rag, on="qid", how="inner")

    helped = merged[
        (merged["no_rag_pred"] != merged["gold"]) &
        (merged["pred"] == merged["gold"])
    ].copy()

    print(f"{rag_method}: {len(helped)} cases where RAG helped")

    for _, row in helped.head(n).iterrows():
        print("\n" + "=" * 100)
        print("QID:", row["qid"])
        print("Question:", row["question"])
        print("Gold:", row["gold"])
        print("No-RAG Pred:", row["no_rag_pred"])
        print(f"{rag_method} Pred:", row["pred"])
        print("Retrieved PMIDs:", row["retrieved_pmids"])

show_rag_helped("semantic_rag", n=5)

semantic_rag: 223 cases where RAG helped

====================================================================================================
QID: 22540518
Question: Is micro-computed tomography reliable to determine the microstructure of the maxillary alveolar bone?
Gold: yes
No-RAG Pred: maybe
semantic_rag Pred: yes
Retrieved PMIDs: ['22540518', '38606694']

====================================================================================================
QID: 20306735
Question: Fulfilling human resources development goal in West Africa: can the training of ophthalmologist diplomates be improved?
Gold: yes
No-RAG Pred: maybe
semantic_rag Pred: yes
Retrieved PMIDs: ['20306735']

====================================================================================================
QID: 21394762
Question: Is pelvic pain associated with defecatory symptoms in women with pelvic organ prolapse?
Gold: yes
No-RAG Pred: unknown
semantic_rag Pred: yes
Retrieved PMIDs: ['21394762', '30576003', '35550798', '40498384', '23575699', '25874639']

====================================================================================================
QID: 23455575
Question: Globulomaxillary cysts--do they really exist?
Gold: no
No-RAG Pred: maybe
semantic_rag Pred: no
Retrieved PMIDs: ['23455575']

====================================================================================================
QID: 18239988
Question: Differentiation of nonalcoholic from alcoholic steatohepatitis: are routine laboratory markers useful?
Gold: yes
No-RAG Pred: maybe
semantic_rag Pred: yes
Retrieved PMIDs: ['18239988', '24675715']

In [ ]:
# =========================
# CASES WHERE RAG HURT
# =========================

def show_rag_hurt(rag_method="semantic_rag", n=5):
    no_rag = pred_df[pred_df["method"] == "no_rag"][["qid", "pred"]].rename(
        columns={"pred": "no_rag_pred"}
    )

    rag = pred_df[pred_df["method"] == rag_method].copy()

    merged = rag.merge(no_rag, on="qid", how="inner")

    hurt = merged[
        (merged["no_rag_pred"] == merged["gold"]) &
        (merged["pred"] != merged["gold"])
    ].copy()

    print(f"{rag_method}: {len(hurt)} cases where RAG hurt")

    for _, row in hurt.head(n).iterrows():
        print("\n" + "=" * 100)
        print("QID:", row["qid"])
        print("Question:", row["question"])
        print("Gold:", row["gold"])
        print("No-RAG Pred:", row["no_rag_pred"])
        print(f"{rag_method} Pred:", row["pred"])
        print("Retrieved PMIDs:", row["retrieved_pmids"])
        print("Error Type:", row["error_type"])

show_rag_hurt("semantic_rag", n=5)

semantic_rag: 37 cases where RAG hurt

====================================================================================================
QID: 16392897
Question: BCRABL transcript detection by quantitative real-time PCR : are correlated results possible from homebrew assays?
Gold: maybe
No-RAG Pred: maybe
semantic_rag Pred: yes
Retrieved PMIDs: ['16392897']
Error Type: generation_failure

====================================================================================================
QID: 20337202
Question: Continuation of pregnancy after antenatal corticosteroid administration: opportunity for rescue?
Gold: maybe
No-RAG Pred: maybe
semantic_rag Pred: yes
Retrieved PMIDs: ['20337202']
Error Type: generation_failure

====================================================================================================
QID: 22227642
Question: Can we measure mesopic pupil size with the cobalt blue light slit-lamp biomicroscopy method?
Gold: no
No-RAG Pred: no
semantic_rag Pred: yes
Retrieved PMIDs: ['22227642']
Error Type: generation_failure

====================================================================================================
QID: 12407608
Question: Does ultrasound imaging before puncture facilitate internal jugular vein cannulation?
Gold: maybe
No-RAG Pred: maybe
semantic_rag Pred: yes
Retrieved PMIDs: ['12407608', '1541105', '16130056', '18942245', '16409336', '7835551']
Error Type: generation_failure

====================================================================================================
QID: 22491528
Question: Combining process indicators to evaluate quality of care for surgical patients with colorectal cancer: are scores consistent with short-term outcome?
Gold: maybe
No-RAG Pred: maybe
semantic_rag Pred: no
Retrieved PMIDs: ['22491528']
Error Type: generation_failure

In [9]:
import nbformat

file_path = "/content/PubMedQA_CBR_RAG_Gemma_Evaluation.ipynb"

nb = nbformat.read(file_path, as_version=4)

# Remove problematic widget metadata
if "widgets" in nb.metadata:
    del nb.metadata["widgets"]

nbformat.write(nb, file_path)

print("Notebook cleaned and fixed!")

FileNotFoundError: [Errno 2] No such file or directory: '/content/PubMedQA_CBR_RAG_Gemma_Evaluation.ipynb'